import { VoteGroupTypeClientEnum } from '../enums/vote.enum';
import { PollTemplateClientType } from '../types/polls.type';

export const POLL_TEMPLATES: Array<PollTemplateClientType> = [
    {
        id: 0,
        type: VoteGroupTypeClientEnum.Choice,
        name: 'Trắc nghiệm - Mẫu 1',
        numberAnswers: 1,
        dragDrop: true,
        preview: 'assets/images/poll-preview/choice-1.jpg',
        min: 1,
        max: 50,
    },
    {
        id: 1,
        type: VoteGroupTypeClientEnum.Choice,
        name: 'Trắc nghiệm - Mẫu 2',
        numberAnswers: 1,
        dragDrop: true,
        preview: 'assets/images/poll-preview/choice-2.jpg',
        min: 1,
        max: 50,
    },
    {
        id: 2,
        type: VoteGroupTypeClientEnum.Choice,
        name: 'Trắc nghiệm - Mẫu 3',
        numberAnswers: 1,
        dragDrop: true,
        preview: 'assets/images/poll-preview/choice-3.jpg',
        min: 1,
        max: 50,
    },
    {
        id: 3,
        type: VoteGroupTypeClientEnum.Choice,
        name: 'Trắc nghiệm - Mẫu 4',
        numberAnswers: 1,
        dragDrop: true,
        preview: 'assets/images/poll-preview/choice-4.jpg',
        min: 1,
        max: 50,
    },
    {
        id: 4,
        type: VoteGroupTypeClientEnum.Choice,
        name: 'Trắc nghiệm - Mẫu 5',
        numberAnswers: 1,
        dragDrop: true,
        preview: 'assets/images/poll-preview/choice-5.jpg',
        min: 1,
        max: 50,
    },
    {
        id: 5,
        type: VoteGroupTypeClientEnum.Choice,
        name: 'Trắc nghiệm - Mẫu 6',
        numberAnswers: 1,
        dragDrop: true,
        preview: 'assets/images/poll-preview/choice-6.jpg',
        min: 1,
        max: 50,
    },
    {
        id: 6,
        type: VoteGroupTypeClientEnum.Rate,
        name: 'Đánh giá sao - Mẫu 1 icon like',
        numberAnswers: 5,
        dragDrop: false,
        preview: 'assets/images/poll-preview/rate-1.jpg',
        min: 2,
        max: 5,
    },
    {
        id: 7,
        type: VoteGroupTypeClientEnum.Rate,
        name: 'Đánh giá sao - Mẫu 1 icon mặt cười',
        numberAnswers: 5,
        dragDrop: false,
        preview: 'assets/images/poll-preview/rate-2.jpg',
        min: 2,
        max: 5,
    },
    {
        id: 8,
        type: VoteGroupTypeClientEnum.Rate,
        name: 'Đánh giá sao - Mẫu 1 icon sao vàng',
        numberAnswers: 5,
        dragDrop: false,
        preview: 'assets/images/poll-preview/rate-3.jpg',
        min: 2,
        max: 5,
    },
    {
        id: 9,
        type: VoteGroupTypeClientEnum.Rate,
        name: 'Đánh giá sao - Mẫu 1 icon trái tim',
        numberAnswers: 5,
        dragDrop: false,
        preview: 'assets/images/poll-preview/rate-4.jpg',
        min: 2,
        max: 5,
    },
    {
        id: 10,
        type: VoteGroupTypeClientEnum.Rate,
        name: 'Đánh giá sao - Mẫu 2 icon like',
        numberAnswers: 5,
        dragDrop: false,
        preview: 'assets/images/poll-preview/rate-5.jpg',
        min: 2,
        max: 5,
    },
    {
        id: 11,
        type: VoteGroupTypeClientEnum.Rate,
        name: 'Đánh giá sao - Mẫu 2 icon mặt cười',
        numberAnswers: 5,
        dragDrop: false,
        preview: 'assets/images/poll-preview/rate-6.jpg',
        min: 2,
        max: 5,
    },
    {
        id: 12,
        type: VoteGroupTypeClientEnum.Rate,
        name: 'Đánh giá sao - Mẫu 2 icon sao vàng',
        numberAnswers: 5,
        dragDrop: false,
        preview: 'assets/images/poll-preview/rate-7.jpg',
        min: 2,
        max: 5,
    },
    {
        id: 13,
        type: VoteGroupTypeClientEnum.Rate,
        name: 'Đánh giá sao - Mẫu 2 icon trái tim',
        numberAnswers: 5,
        dragDrop: false,
        preview: 'assets/images/poll-preview/rate-8.jpg',
        min: 2,
        max: 5,
    },
    {
        id: 14,
        type: VoteGroupTypeClientEnum.Rate,
        name: 'Đánh giá sao - Mẫu 3 icon like',
        numberAnswers: 5,
        dragDrop: false,
        preview: 'assets/images/poll-preview/rate-9.jpg',
        min: 2,
        max: 5,
    },
    {
        id: 15,
        type: VoteGroupTypeClientEnum.Rate,
        name: 'Đánh giá sao - Mẫu 3 icon mặt cười',
        numberAnswers: 5,
        dragDrop: false,
        preview: 'assets/images/poll-preview/rate-10.jpg',
        min: 2,
        max: 5,
    },
    {
        id: 16,
        type: VoteGroupTypeClientEnum.Rate,
        name: 'Đánh giá sao - Mẫu 3 icon sao vàng',
        numberAnswers: 5,
        dragDrop: false,
        preview: 'assets/images/poll-preview/rate-11.jpg',
        min: 2,
        max: 5,
    },
    {
        id: 17,
        type: VoteGroupTypeClientEnum.Rate,
        name: 'Đánh giá sao - Mẫu 3 icon trái tim',
        numberAnswers: 5,
        dragDrop: false,
        preview: 'assets/images/poll-preview/rate-12.jpg',
        min: 2,
        max: 5,
    },
    {
        id: 18,
        type: VoteGroupTypeClientEnum.Rate,
        name: 'Đánh giá sao - Mẫu 4 icon like',
        numberAnswers: 5,
        dragDrop: false,
        preview: 'assets/images/poll-preview/rate-13.jpg',
        min: 2,
        max: 5,
    },
    {
        id: 19,
        type: VoteGroupTypeClientEnum.Rate,
        name: 'Đánh giá sao - Mẫu 4 icon mặt cười',
        numberAnswers: 5,
        dragDrop: false,
        preview: 'assets/images/poll-preview/rate-14.jpg',
        min: 2,
        max: 5,
    },
    {
        id: 20,
        type: VoteGroupTypeClientEnum.Rate,
        name: 'Đánh giá sao - Mẫu 4 icon sao vàng',
        numberAnswers: 5,
        dragDrop: false,
        preview: 'assets/images/poll-preview/rate-15.jpg',
        min: 2,
        max: 5,
    },
    {
        id: 21,
        type: VoteGroupTypeClientEnum.Rate,
        name: 'Đánh giá sao - Mẫu 4 icon trái tim',
        numberAnswers: 5,
        dragDrop: false,
        preview: 'assets/images/poll-preview/rate-16.jpg',
        min: 2,
        max: 5,
    },
    {
        id: 22,
        type: VoteGroupTypeClientEnum.LinearRange,
        name: 'Phạm vi tuyến tính - mẫu 1',
        numberAnswers: 10,
        dragDrop: false,
        preview: 'assets/images/poll-preview/range-1.jpg',
        min: 2,
        max: 10,
    },
    {
        id: 23,
        type: VoteGroupTypeClientEnum.LinearRange,
        name: 'Phạm vi tuyến tính - mẫu 2',
        numberAnswers: 10,
        dragDrop: false,
        preview: 'assets/images/poll-preview/range-2.jpg',
        min: 2,
        max: 10,
    },
    {
        id: 24,
        type: VoteGroupTypeClientEnum.LinearRange,
        name: 'Phạm vi tuyến tính - mẫu 3',
        numberAnswers: 10,
        dragDrop: false,
        preview: 'assets/images/poll-preview/range-3.jpg',
        min: 2,
        max: 10,
    },
    {
        id: 25,
        type: VoteGroupTypeClientEnum.LinearRange,
        name: 'Phạm vi tuyến tính - mẫu 4',
        numberAnswers: 10,
        dragDrop: false,
        preview: 'assets/images/poll-preview/range-4.jpg',
        min: 2,
        max: 10,
    },
];
