import React from "react";
import { FederationAppInitProps } from "./federation.type";

export type CommonBaseReducerState<T = unknown> = {
  models: Array<T>;
  model: T;
  metaData?: {
    pageIndex: number;
    pageSize: number;
    totalRow: number;
  };
};
export type CommonBaseListDetailReducerState<
  ListType = unknown,
  DetailType = unknown
> = {
  models: Array<ListType>;
  model?: DetailType;
  metaData?: {
    pageIndex: number;
    pageSize: number;
    totalRow: number;
  };
};
export type LoadingActionSliceState = {
  get: boolean;
  post: boolean;
  put: boolean;
  delete: boolean;
  appointmentTypeGetById: boolean;
  appointmentTypeAndOrChange: boolean;
  appointmentTypeDealerMappingChange: boolean;
  TestDriveTypeGetById: boolean;
  TestDriveTypeAndOrChange: boolean;
  loyaltyCustomerByVoucher: boolean;
  loyaltyCustomerPointMappingList: boolean;
  loyaltyVoucherOfCustomerMappingList: boolean;
  loyaltyVoucherList: boolean;
  loyaltyVoucherCreateOrUpdate: boolean;
  loyaltyVoucherRedeemPoint: boolean;
  loyaltyVoucherClaimReward: boolean;
  loyaltyVoucherDelete: boolean;
  integrationLogList: boolean;
  integrationLogById: boolean;
  integrationLogGetFieldValue: boolean;
  ecareTicketList: boolean;
  ecareTicketSyncToEs: boolean;
  ecareTicketAdd: boolean;
  ecareTicketChange: boolean;
  ecareTicketDelete: boolean;
  ecareTicketDetail: boolean;
  ecareTicketConfigCode: boolean;
  ecareTicketGetUser: boolean;
  ecareTicketGetDealer: boolean;
  ecareTicketInsertAdditional: boolean;
  additionalInformationList: boolean;
  additionalInformationDetail: boolean;
  additionalInformationAdd: boolean;
  additionalInformationChange: boolean;
  claimContentList: boolean;
  claimContentDetail: boolean;
  claimContentAdd: boolean;
  claimContentChange: boolean;
  claimContentDelete: boolean;
  wngList: boolean;
  wngDetail: boolean;
  wngAdd: boolean;
  wngChange: boolean;
  ecareTicketSearchByPhoneOrCarPlate: boolean;
  ecareTicketGetSQVehicleById: boolean;
  ecareTicketGetSQVehicleByCustId: boolean;
  ecareMergeTicket: boolean;
  ecareMassTicket: boolean;
  ecareTicketGetConfigByParentId: boolean;
  addComment: boolean;
  commentList: boolean;
  insurancePriceConfigSearch: boolean;
  priceConfigSearch: boolean;
  loyaltyCardSearch: boolean;
  wngListMaster: boolean;
  wngListHistory: boolean;
  ecareTicketStolenTracking: boolean;
  wngDelete: boolean;
  ecareTicketGetSimStatus: boolean;
  ecareTicketGetContractService: boolean;
  ecareTicketStartOrStopEngine: boolean;
  loyaltyServiceCategoryDelete: boolean;
  loyaltyServiceCategoryChange: boolean;
  loyaltyServiceCategoryAdd: boolean;
  loyaltyServiceCategoryDetail: boolean;
  loyaltyServiceCategoryList: boolean;
  policyPointRule: boolean;
  upsertLoyaltyCard: boolean;
  voucherForCard: boolean;
  deleteLoyaltyCard: boolean;
  pointRuleSearch: boolean;
  upsertPointRule: boolean;
  modelCard: boolean;
  loyaltyBrandRemove: boolean;
  loyaltyBranchLookup: boolean;
  loyaltyBrandAddOrChange: boolean;
  loyaltyBrandModel: boolean;
  loyaltyBrandModels: boolean;
  loyaltyFAQDelete: boolean;
  loyaltyFAQChange: boolean;
  loyaltyFAQAdd: boolean;
  loyaltyFAQDetail: boolean;
  loyaltyFAQList: boolean;
  loyaltyNotificationSearch: boolean;
  loyaltyNotificationGet: boolean;
  loyaltyNotificationAddOrChange: boolean;
  deletePointRule: boolean;
  loyaltyCardDetail: boolean;
  GetNextMaxSortOrderNumber: boolean;
  GetTransactionCode: boolean;
  loyaltyCustomer: boolean;
  loyaltyCustomerGender: boolean;
  loyaltyCustomerProvince: boolean;
  loyaltyCustomerDistrict: boolean;
  loyaltyCustomerSearchCard: boolean;
  loyaltyCustomerSelectCard: boolean;
  loyaltyCustomerByUserSelectCard: boolean;
  loyaltyNotifycationGetData: boolean;
  loyaltyMTHGetUserByROCode: boolean;
  loyaltyUserGetNotificationByUserId: boolean;
  loyaltyUserGetChangePointHistoriesByUserId: boolean;
  loyaltyUserGetChangeLevelHistoriesByUserId: boolean;
  loyaltyUserGetVoucherHistoriesByUserId: boolean;
  loyaltyUserGetCampaignHistoriesByUserId: boolean;
  loyaltyUserGetTouchPointHistoriesByUserId: boolean;
  loyaltyUserGetSearchCustomer: boolean;
  loyaltyCustomerExportCus: boolean;
  loyaltyCustomerExportNotifycation: boolean;
  loyaltyCustomerExportChangePointHistories: boolean;
  loyaltyCustomerExportVoucherHistories: boolean;
  loyaltyCustomerExportCampaignHistoriesList: boolean;
  loyaltyUserDownloadFileImportCustomer: boolean;
  loyaltyCustomerImportFileUser: boolean;
  loyaltyCustomerAdd: boolean;
  loyaltyCustomerChange: boolean;
  loyaltyCustomerEditPersonalInfo: boolean;
  loyaltyCustomerEditIdCard: boolean;
  loyaltyUserAddOrChange: boolean;
  loyaltyCustomerDetail: boolean;
  loyaltyCustomerDelete: boolean;
  loyaltyCustomerAddNoti: boolean;
  loyaltyCustomerAddPoint: boolean;
  loyaltyGetCardsByUserId: boolean;
  loyaltyCustomerChangeStatus: boolean;
  loyaltyCustomerChangeMethodContact: boolean;
  loyaltyUserGet: boolean;
  loyaltyUserlist: boolean;
  loyaltyUserSearch: boolean;
  cardMembershipSearch: boolean;
  insertMemberships: boolean;
  ecareTicketGetJudgeByVin: boolean;
  loyaltyFAQGetNextMaxSortOrderNumber: boolean;
  loyaltyMemberGroupDelete: boolean;
  loyaltyMemberGroupAdd: boolean;
  loyaltyMemberGroupChange: boolean;
  loyaltyMemberGroupDetail: boolean;
  loyaltyMemberGroupList: boolean;
  loyaltyMemberGroupProvinceAutocomplete: boolean;
  loyaltyMemberGroupGetCardByDealerId: boolean;
  ecareTicketGetNotiECall: boolean;
  loyaltyMemberTransactionHistorySearch: boolean;
  ecareTicketListWhenMerge: boolean;
  loyaltyMemberPointHistorySearch: boolean;
  loyaltyCardSelectControl: boolean;
  loyaltyCardLevelSelectControl: boolean;
  loyaltyComplaintList: boolean;
  loyaltyComplaintDetail: boolean;
  loyaltyComplaintAnswer: boolean;
  loyaltyRemoveDelete: boolean;
  ecareTicketGetCsExpiredDateByVin: boolean;
  loyaltyMemberGroupMemberList: boolean;
  GetLoyaltyCardForSelect: boolean;
  loyaltyMemberGroupExport: boolean;
  loyaltyMemberGroupGetServiceOptions: boolean;
  ecareTicketGetVehiclePosition: boolean;
  loyaltyCardMembershipLevelHistoryChangeStatus: boolean;
  loyaltyCardMembershipLevelHistoryExport: boolean;
  loyaltySendOtpToCustomer: boolean;
  loyaltyVerifyOtp: boolean;
  ecareTicketGetEngineStatusByVin: boolean;
  loyaltyComplaintChangePoint: boolean;
};

export type CommonReducerState = {
  process: {
    listLoading: boolean;
    actionLoading: Partial<LoadingActionSliceState>;
  };
  error: {
    messages: Array<string>;
    statusCode: number;
  };
  federationResolver: FederationAppInitProps;
  onShowDialogModalLarge: (params: CommonModalPropsConfiguration) => void;
  onShowDialogModalMedium: (params: CommonModalPropsConfiguration) => void;
  onShowDialogModalSmall: (params: CommonModalPropsConfiguration) => void;
  moduleConfig?: {
    moduleName: string;
    prefixClass: string;
    appVersion: string;
  };
  count: number;
};

export type CommonModalPropsConfiguration = {
  title?: React.ReactNode;
  component: React.ElementType<React.ReactElement, any>;
  afterClose?: () => void;
  closable?: boolean;
  data?: any;
  dataUi?: any;
  width?: number | string;
};
